In [39]:
import numpy as np
import random

# NUMPY PROJECTS 


In [118]:
employees = 20
print("TOTAL_EMPLOYES-",employees)
np.random.seed(0)
emp_ids = np.arange(1,employees + 1) 
ages = np.random.randint(21, 61, 20)
dept_ids = np.random.randint(1, 6, 20)
monthly_salary = np.random.randint(25000, 120001, 20)
sales_units = np.random.randint(0, 51, 20)

data = np.column_stack((emp_ids, ages, dept_ids, monthly_salary, sales_units))
print("         === EMPLOYEE DATA ===")
print("------------------------------------------")
print("[      ID    Age   Dept  Salary  Sales]")
print("------------------------------------------")
print(data[0:5])
print("------------------------------------------")
print("AGES OF FIRST 5 EMPLOYESS")
print(data[:5,1])
print("SALARIES OF every 2nd MEMBERS")
print(data[ : : 2,3])
print("SALARY ABOVE 80K")
print(data[monthly_salary > 80000])
print("Employees in Dept 3 with sales > 30")
print(data[(sales_units > 30) & (dept_ids == 3)])
print(f"avg salary",np.average(monthly_salary))
print("max salary",np.max(monthly_salary))
print("total sales",np.sum(sales_units))
print("lowest 3 salaries")
low = np.argsort(data[ : ,3])
print(data[low][:3])
print("top sales")
hig = np.argsort(data[: ,4])[ : : -1]
print(data[hig[ : 3]])
print("YEARLY SALARY")
y_s = data[: ,3]*12
print("ID , YEARLY_SALARY")
print(np.column_stack((data[:,0],y_s)))
performance = np.where(data[:, 4] > 25, "High", "Low")
print("\nPerformance Tags:\n", performance)

unique_depts, dept_counts = np.unique(data[:, 2], return_counts=True)
print("\nUnique Departments:", unique_depts)
print("Employees per Dept:", dept_counts)
print('-----------------------------------------------------------')
print("Total Employees:", len(data))
print("Average Salary:", np.average(monthly_salary))
print("Employees earning > 80k:", np.sum(data[:, 3] > 80000))
print("Top Sales Employee ID:", data[np.argmax(data[:, 4]), 0])
print('-----------------------------------------------------------')

TOTAL_EMPLOYES- 20
         === EMPLOYEE DATA ===
------------------------------------------
[      ID    Age   Dept  Salary  Sales]
------------------------------------------
[[     1     21      2  74866     35]
 [     2     24      1 109212     38]
 [     3     24      2  36723     11]
 [     4     60      5  68890     46]
 [     5     30      4  42591     18]]
------------------------------------------
AGES OF FIRST 5 EMPLOYESS
[21 24 24 60 30]
SALARIES OF every 2nd MEMBERS
[ 74866  36723  42591 117288 114141  45006 115868  70444 111904  53647]
SALARY ABOVE 80K
[[     2     24      1 109212     38]
 [     6     40      1  83146     27]
 [     7     42      4 117288      0]
 [     8     57      1  84300     14]
 [     9     44      3 114141     35]
 [    10     27      4  96557     12]
 [    13     33      4 115868     11]
 [    14     22      4  86713      4]
 [    17     44      2 111904     47]
 [    20     58      1  86353     36]]
Employees in Dept 3 with sales > 30
[[     9   